collections:
  reviews:
    output: true
    path: "reviews/{filename}.md"
    label: "Drink Reviews"
    icon: drink
    fields:
      - type: text
        name: title
        label: Title
      - type: datetime
        name: date
        label: Date
      - type: select
        name: type
        label: Drink Type
        options:
          - Soda
          - Energy Drink
          - Juice
          - Water
      - type: number
        name: rating
        label: Rating
        min: 1
        max: 10
      - type: markdown
        name: body
        label: Review

# Optional: For future editable fields in index.html or about.html
pages:
  index.html:
    label: Homepage
    fields:
      - type: text
        name: header
        label: Welcome Header
      - type: text
        name: subheading
        label: Subheading / Tagline

timezone: Europe/Paris
