backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Drink Type", name: "type", widget: "select", options: ["Soda", "Energy Drink", "Juice", "Water"] }
      - { label: "Rating", name: "rating", widget: "number", min: 1, max: 10 }
      - { label: "Body", name: "body", widget: "markdown" }
