backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

site_url: https://tastonaut.netlify.app
logo_url: /img/logo.png

collections:
  - name: "reviews"
    label: "Reviews"
    folder: "reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "about.njk"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - label: "Homepage"
        name: "homepage"
        file: "index.njk"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Intro Text", name: "intro", widget: "text" }
